### ISSUE TITLE
AttributeError when running script

### ISSUE THREAD

**Issue by annathemusicalfruit** [aliasoblomov/Backfill-GA4-to-BigQuery#1]
Hello! Thanks so much for the script. Already a great help!

I've got an issue after running the python script though, please see below:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/content/backfill-ga4.py](https://localhost:8080/#) in <module>
    165 )
    166 
--> 167 active_users = run_report_with_pagination(client, request_active_users)
    168 
    169 request_events = RunReportRequest(

3 frames
[/usr/local/lib/python3.10/dist-packages/google/analytics/data_v1beta/services/beta_analytics_data/client.py](https://localhost:8080/#) in _compare_universes(client_universe, credentials)
    494         """
    495         if credentials:
--> 496             credentials_universe = credentials.universe_domain
    497             if client_universe != credentials_universe:
    498                 default_universe = BetaAnalyticsDataClient._DEFAULT_UNIVERSE

AttributeError: 'Credentials' object has no attribute 'universe_domain'

Please can you help me work out how to fix this?

**Comment by aliasoblomov** [comment]
Hi, 
it is because of a compatibility issue between the version of the google-auth library you're using and the google-analytics-data library. upgrade your libraries can fix the issue.

`!pip install --upgrade google-analytics-data google-auth
`

**Comment by annathemusicalfruit** [comment]
Thanks so much for coming back so quickly! 
I'm still getting the same issue though, weirdly, have I done something wrong here?

!pip install --upgrade google-analytics-data google-auth
!pip install google-auth-oauthlib
!pip install google-cloud-bigquery
!pip install google-auth-httplib2

**Comment by aliasoblomov** [comment]
There is no need to install any additional libraries again. Simply run my command before running the main script. I encountered the same issue in Colab and resolved it by upgrading the libraries.

**Comment by annathemusicalfruit** [comment]
You are wonderful - thanks so much!

**Comment by aliasoblomov** [comment]
Thank you for your feedback. I have updated the readme file with compatible library versions. Please check it again to see if your issue is resolved.
