### ISSUE TITLE
localhost refused to connect on first run

### ISSUE THREAD

**Issue by iampatgrady** [aliasoblomov/Backfill-GA4-to-BigQuery#3]
Hi, 

Cloning, configuring as per your Readme, then running for the first time with --initial_fetch flag returns this error after going through the OAUTH flow:

```
This site can’t be reached
localhost refused to connect.
```

The URL is: http://localhost:8080/ ....

This fails both locally and using Google Colab. 

If there is a requirement to run a localhost server then it is missing from the documentation.  I'm unclear how to proceed. Apologies I'm not skilled enough with code to try to debug this.

**Comment by aliasoblomov** [comment]
Hi,
As explained in the readme file, you can find the code in the Localhost URL. However, this URL is invalid and you shouldn't expect to see any results on it.check the readme file again please.
