### ISSUE TITLE
Schema?

### ISSUE THREAD

**Issue by efrazier** [aliasoblomov/Backfill-GA4-to-BigQuery#4]
Thanks for making this open. I don't see any place where I can find the resulting schema in BigQuery? The main issue with any of these backfills so far, is just that they don't match the default import stream, which makes for a lot of work to actually stitch queries together. 

Thanks!

**Comment by aliasoblomov** [comment]
Unfortunately, GA4 API doesn't allow the extraction of granular data, such as all events of specific users. As a result, the data available is aggregated, but you can adjust it with your desired metrics and dimensions.

**Comment by efrazier** [comment]
Thanks, but I know that. I just mean what is the resulting schema that you
are writing now?

**Comment by aliasoblomov** [comment]
I have attached a screenshot of the results table. Also you can customize the schema according to your analytics needs.

**Comment by efrazier** [comment]
Thanks, but I don't see a screenshot?

**Comment by aliasoblomov** [comment]
https://github.com/aliasoblomov/Backfill-GA4-to-BigQuery/blob/main/backfill-GA4-schema.md
