### ISSUE TITLE
Feature Request (Wish) - Backfill to Existing GA4 to BigQuery Connector Dataset/Table 

### ISSUE THREAD

**Issue by shilojones** [aliasoblomov/Backfill-GA4-to-BigQuery#8]
@aliasoblomov - do you think it is technically possible to backfill GA4 data into the same dataset/table that is created when you establish the BigQuery link in GA4?

![ga4Backfill](https://github.com/aliasoblomov/Backfill-GA4-to-BigQuery/assets/126340129/99ee179d-bd33-4be1-9983-974fe5b2f481)

**Comment by shilojones** [comment]
This seems to be the default structure when setting up the BigQuery link in GA4 and I would believe that adding this functionality would be of a huge value to folks.  If possible, I'd love to help in whatever way I can.

**Comment by aliasoblomov** [comment]
It is possible to add data to the analytics dataset, but you cannot merge or replace it with event-sharded tables using this script.
