### ISSUE TITLE
No data to insert.

### ISSUE THREAD

**Issue by wishyrater** [aliasoblomov/Backfill-GA4-to-BigQuery#9]
> Authentication successful!

> Data saved to output.csv!

> No data to insert.

I have verified the account I am using to authenticate has read access to the GA4-property, but no data is appearing in the output.csv-file.

Any suggestions?

**Comment by Hossein-Ak** [comment]
Did you connect your BigQuery to the correct ga4?

**Comment by aliasoblomov** [comment]
It may be because no data exists for the property, date range, or combination of dimensions and metrics set in the config.json file.
